In [1]:
import sys
import os

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import numpy as np
from src.MonteCarloSphere import MonteCarloSphere
from src.MonteCarloSphereFreeFermions import MonteCarloSphereFreeFermions
from src.MonteCarloTorusFreeFermions import MonteCarloTorusFreeFermions

In [6]:
ff = MonteCarloSphereFreeFermions(Ne=9, Ns=16, nbr_iter=200000, nbr_nonthermal=50000, region_geometry='circle', step_size=0.12, region_size=0.05, linear_size=True, nbr_copies=2, save_config=False, save_results=False)

In [7]:
ff.RunSwapMod()

Iteration 10000 done, current acceptance ratio: 48.87 %
Iteration 20000 done, current acceptance ratio: 49.44 %
Iteration 30000 done, current acceptance ratio: 49.29 %
Iteration 40000 done, current acceptance ratio: 49.27 %
Iteration 50000 done, current acceptance ratio: 49.25 %
Iteration 60000 done, current acceptance ratio: 49.29 %
Iteration 70000 done, current acceptance ratio: 49.26 %
Iteration 80000 done, current acceptance ratio: 49.27 %
Iteration 90000 done, current acceptance ratio: 49.24 %
Iteration 100000 done, current acceptance ratio: 49.25 %
Iteration 110000 done, current acceptance ratio: 49.27 %
Iteration 120000 done, current acceptance ratio: 49.24 %
Iteration 130000 done, current acceptance ratio: 49.26 %
Iteration 140000 done, current acceptance ratio: 49.27 %
Iteration 150000 done, current acceptance ratio: 49.26 %
Iteration 160000 done, current acceptance ratio: 49.33 %
Iteration 170000 done, current acceptance ratio: 49.32 %
Iteration 180000 done, current acceptanc

In [20]:
f = np.random.randint(0,9,9)

In [23]:
f

array([5, 3, 4, 7, 3, 4, 6, 7, 3])

In [32]:
a = -6.3
a - (np.pi)*(a//np.pi)

3.1247779607693795

In [67]:
def BoundaryConditions(z) -> np.complex128:
        """Check if the particle position wrapped around the torus
        after one step. When a step wraps around both directions,
        the algorithm applies """
        z[..., 1] = z[..., 1] + np.pi*((z[..., 0] > np.pi) | (z[..., 0] < 0))
        z[..., 1] = z[..., 1] - 2*np.pi*(z[..., 1]//(2*np.pi))
        z[..., 0] = z[..., 0] + 2*np.pi*(z[..., 0] > np.pi) - 2*z[..., 0] * \
            ((z[..., 0] > np.pi) | (z[..., 0] < 0))

        return z

In [68]:
BoundaryConditions(np.array([[3.15,5], [1.4, 7]]))

array([[3.13318531, 1.85840735],
       [1.4       , 0.71681469]])

In [47]:
 2*np.pi*(7//(2*np.pi))

6.283185307179586

In [9]:
np.random.Generator.choice(np.array([[1,1],[2,2]]), 1)

TypeError: descriptor 'choice' for 'numpy.random._generator.Generator' objects doesn't apply to a 'int' object

In [11]:
a = np.array([[1,1],[2,2]])
a.choice(2)

AttributeError: 'numpy.ndarray' object has no attribute 'choice'

In [18]:
np.random.default_rng().choice(np.array([[1,1],[2,2], [3,4]]), 2)

array([[2, 2],
       [3, 4]])