In [1]:
import sys
import os

module_path = os.path.abspath(os.path.join('..'))
if module_path not in sys.path:
    sys.path.append(module_path)

import numpy as np
from src.MonteCarloSphere import MonteCarloSphere
from src.MonteCarloSphereFreeFermions import MonteCarloSphereFreeFermions
from src.MonteCarloSphereCFL import MonteCarloSphereCFL
from src.MonteCarloTorusFreeFermions import MonteCarloTorusFreeFermions

d:\fizica\phd\MonteCarlo\MonteCarlo\src\MonteCarloSphereCFL.py:8: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def njit_UpdateJastrows(coords_tmp: np.array, spinors_tmp: np.array,
d:\fizica\phd\MonteCarlo\MonteCarlo\src\MonteCarloSphereCFL.py:23: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
  def njit_UpdateJastrowsSwap(coords_tmp: np.array, spinors_tmp: np.arra

In [2]:
ff = MonteCarloSphereCFL(Ne=9, Ns=16, nbr_iter=20000, nbr_nonthermal=1000, region_geometry='circle', step_size=0.175, region_size=0.1, linear_size=True, nbr_copies=2, save_config=False, save_results=False)

In [3]:
ff.RunSwapMod()

d:\fizica\phd\MonteCarlo\MonteCarlo\src\MonteCarloSphereCFL.py:7: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "njit_UpdateJastrows" failed type inference due to: Untyped global name 'sph_harm': Cannot determine Numba type of <class 'numpy.ufunc'>

File "..\src\MonteCarloSphereCFL.py", line 18:
def njit_UpdateJastrows(coords_tmp: np.array, spinors_tmp: np.array,
    <source elided>

    slater_tmp[:, moved_particle] = sph_harm(
    ^

  @jit
C:\Users\crist\AppData\Roaming\Python\Python310\site-packages\numba\core\object_mode_passes.py:151: NumbaWarning: Function "njit_UpdateJastrows" was compiled in object mode without forceobj=True.

File "..\src\MonteCarloSphereCFL.py", line 8:
@jit
def njit_UpdateJastrows(coords_tmp: np.array, spinors_tmp: np.array,
^

  warnings.warn(errors.NumbaWarning(warn_msg,
C:\Users\crist\AppData\Roaming\Python\Python310\site-packages\numba\core\object_mode_passes.py:161: NumbaDeprecationWarning: 
Fall-ba

Iteration 1000 done, current acceptance ratio: 32.0 %
Iteration 2000 done, current acceptance ratio: 31.4 %
Iteration 3000 done, current acceptance ratio: 38.57 %
Iteration 4000 done, current acceptance ratio: 45.3 %
Iteration 5000 done, current acceptance ratio: 44.04 %
Iteration 6000 done, current acceptance ratio: 40.42 %
Iteration 7000 done, current acceptance ratio: 39.2 %
Iteration 8000 done, current acceptance ratio: 38.45 %
Iteration 9000 done, current acceptance ratio: 36.84 %
Iteration 10000 done, current acceptance ratio: 37.23 %
Iteration 11000 done, current acceptance ratio: 37.08 %
Iteration 12000 done, current acceptance ratio: 37.75 %
Iteration 13000 done, current acceptance ratio: 38.25 %
Iteration 14000 done, current acceptance ratio: 37.76 %
Iteration 15000 done, current acceptance ratio: 39.15 %
Iteration 16000 done, current acceptance ratio: 38.88 %
Iteration 17000 done, current acceptance ratio: 37.22 %
Iteration 18000 done, current acceptance ratio: 35.16 %
Itera

In [5]:
np.array([1, np.sin(ff.coords_tmp[1][0])])

array([1.        , 0.42537869])

In [20]:
f = np.random.randint(0,9,9)

In [23]:
f

array([5, 3, 4, 7, 3, 4, 6, 7, 3])

In [32]:
a = -6.3
a - (np.pi)*(a//np.pi)

3.1247779607693795

In [67]:
def BoundaryConditions(z) -> np.complex128:
        """Check if the particle position wrapped around the torus
        after one step. When a step wraps around both directions,
        the algorithm applies """
        z[..., 1] = z[..., 1] + np.pi*((z[..., 0] > np.pi) | (z[..., 0] < 0))
        z[..., 1] = z[..., 1] - 2*np.pi*(z[..., 1]//(2*np.pi))
        z[..., 0] = z[..., 0] + 2*np.pi*(z[..., 0] > np.pi) - 2*z[..., 0] * \
            ((z[..., 0] > np.pi) | (z[..., 0] < 0))

        return z

In [68]:
BoundaryConditions(np.array([[3.15,5], [1.4, 7]]))

array([[3.13318531, 1.85840735],
       [1.4       , 0.71681469]])

In [47]:
 2*np.pi*(7//(2*np.pi))

6.283185307179586

In [9]:
np.random.Generator.choice(np.array([[1,1],[2,2]]), 1)

TypeError: descriptor 'choice' for 'numpy.random._generator.Generator' objects doesn't apply to a 'int' object

In [11]:
a = np.array([[1,1],[2,2]])
a.choice(2)

AttributeError: 'numpy.ndarray' object has no attribute 'choice'

In [18]:
np.random.default_rng().choice(np.array([[1,1],[2,2], [3,4]]), 2)

array([[2, 2],
       [3, 4]])